### ISSUE TITLE
关于树形表格查询和数据表格底部统计

### ISSUE THREAD

**Issue by Mine-MuYan** [jqhph/dcat-admin-demo#11]
### 树形表格查询
使用场景如下：
用户列表，有一个按钮可以以树形图形式展示这个用户下所有的团队成员。
用户的上下级关系如下：
![image](https://user-images.githubusercontent.com/23254569/104880784-2e81e600-599b-11eb-8a35-bef9769aa633.png)

ID为1的用户其parent_id=0，展示出来的关系是完整的，但当点击他的下级，如2、3时，弹出来的模态框就会提示无数据。

### 定义footer后，分页统计的footer不消失
```php
$grid->footer(function ($collection) {
    $count = UserRepository::getUserTeamCount($this->userId);
    
    return "<div>团队总人数 ： $count 人</div>";
});
```

辛苦了。:coffee:

**Comment by jqhph** [comment]
Dcat Admin的相关问题请前往 https://github.com/jqhph/dcat-admin/issues 提交，感谢配合
