### ISSUE TITLE
Admin Routes Undefined after composer install

### ISSUE THREAD

**Issue by cyruscode19** [jqhph/dcat-admin-demo#3]
Generating optimized autoload files
> post-autoload-dump: Illuminate\Foundation\ComposerScripts::postAutoloadDump
> post-autoload-dump: @php artisan package:discover --ansi
Executing command (CWD): "C:\xampp\php\php.exe" -d allow_url_fopen="1" -d disable_functions="" -d memory_limit="1536M" artisan package:discover --ansi

In routes.php line 7:

  Call to undefined method Dcat\Admin\Admin::routes()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by jqhph** [comment]
Hello,this bug has been fixed, please update the latest version of the master branch.
